<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>flask.cli.NoAppException: While importing &#x27;app&#x27;, an ImportError was raised. // Werkzeug Debugger</title>
    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css"
        type="text/css">
    <!-- We need to make sure this has a favicon so that the debugger does
         not accidentally trigger a request to /favicon.ico which might
         change the application's state. -->
    <link rel="shortcut icon"
        href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
    <script src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
    <script type="text/javascript">
      var TRACEBACK = 140329219753968,
          CONSOLE_MODE = false,
          EVALEX = true,
          EVALEX_TRUSTED = false,
          SECRET = "kNJM05Ezk3tWs6zNMWtK";
    </script>
  </head>
  <body style="background-color: #fff">
    <div class="debugger">
<h1>flask.cli.NoAppException</h1>
<div class="detail">
  <p class="errormsg">flask.cli.NoAppException: While importing &#x27;app&#x27;, an ImportError was raised.</p>
</div>
<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>
<div class="traceback">
  <h3></h3>
  <ul><li><div class="frame" id="frame-140329219753104">
  <h4>File <cite class="filename">"/home/gsej/repos/polytunnel-monitor/webapi/app.py"</cite>,
      line <em class="line">9</em>,
      in <code class="function">&lt;module&gt;</code></h4>
  <div class="source "><pre class="line before"><span class="ws"></span>from flask_cors import CORS, cross_origin</pre>
<pre class="line before"><span class="ws"></span>import os</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws"></span>from current_temperatures import readInsideTemperature, readOutsideTemperature</pre>
<pre class="line before"><span class="ws"></span>from pistats import Stats</pre>
<pre class="line current"><span class="ws"></span>from temperature_data import getTemperatureData, getTemperatureDataRange,getTemperatureDataRangeDb</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span>app = Flask(__name__)</pre>
<pre class="line after"><span class="ws"></span>cors = CORS(app)</pre>
<pre class="line after"><span class="ws"></span>app.config[&#x27;CORS_HEADERS&#x27;] = &#x27;Content-Type&#x27;</pre>
<pre class="line after"><span class="ws"></span> </pre></div>
</div>

<li><div class="exc-divider">The above exception was the direct cause of the following exception:</div>
<li><div class="frame" id="frame-140329219753392">
  <h4>File <cite class="filename">"/home/gsej/repos/polytunnel-monitor/venv/lib/python3.10/site-packages/flask/cli.py"</cite>,
      line <em class="line">363</em>,
      in <code class="function">__call__</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">        </span>self._flush_bg_loading_exception()</pre>
<pre class="line before"><span class="ws">        </span>with self._lock:</pre>
<pre class="line before"><span class="ws">            </span>if self._app is not None:</pre>
<pre class="line before"><span class="ws">                </span>rv = self._app</pre>
<pre class="line before"><span class="ws">            </span>else:</pre>
<pre class="line current"><span class="ws">                </span>rv = self._load_unlocked()</pre>
<pre class="line after"><span class="ws">            </span>return rv(environ, start_response)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span>class ScriptInfo:</pre>
<pre class="line after"><span class="ws">    </span>&quot;&quot;&quot;Helper object to deal with Flask applications.  This is usually not</pre></div>
</div>

<li><div class="frame" id="frame-140329219753248">
  <h4>File <cite class="filename">"/home/gsej/repos/polytunnel-monitor/venv/lib/python3.10/site-packages/flask/cli.py"</cite>,
      line <em class="line">350</em>,
      in <code class="function">_load_unlocked</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">            </span>self._bg_loading_exc = None</pre>
<pre class="line before"><span class="ws">            </span>raise exc</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">    </span>def _load_unlocked(self):</pre>
<pre class="line before"><span class="ws">        </span>__traceback_hide__ = True  # noqa: F841</pre>
<pre class="line current"><span class="ws">        </span>self._app = rv = self.loader()</pre>
<pre class="line after"><span class="ws">        </span>self._bg_loading_exc = None</pre>
<pre class="line after"><span class="ws">        </span>return rv</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def __call__(self, environ, start_response):</pre>
<pre class="line after"><span class="ws">        </span>__traceback_hide__ = True  # noqa: F841</pre></div>
</div>

<li><div class="frame" id="frame-140329219753008">
  <h4>File <cite class="filename">"/home/gsej/repos/polytunnel-monitor/venv/lib/python3.10/site-packages/flask/cli.py"</cite>,
      line <em class="line">406</em>,
      in <code class="function">load_app</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">            </span>if self.app_import_path:</pre>
<pre class="line before"><span class="ws">                </span>path, name = (</pre>
<pre class="line before"><span class="ws">                    </span>re.split(r&quot;:(?![\\/])&quot;, self.app_import_path, 1) + [None]</pre>
<pre class="line before"><span class="ws">                </span>)[:2]</pre>
<pre class="line before"><span class="ws">                </span>import_name = prepare_import(path)</pre>
<pre class="line current"><span class="ws">                </span>app = locate_app(self, import_name, name)</pre>
<pre class="line after"><span class="ws">            </span>else:</pre>
<pre class="line after"><span class="ws">                </span>for path in (&quot;wsgi.py&quot;, &quot;app.py&quot;):</pre>
<pre class="line after"><span class="ws">                    </span>import_name = prepare_import(path)</pre>
<pre class="line after"><span class="ws">                    </span>app = locate_app(self, import_name, None, raise_if_not_found=False)</pre>
<pre class="line after"><span class="ws"></span> </pre></div>
</div>

<li><div class="frame" id="frame-140329219752960">
  <h4>File <cite class="filename">"/home/gsej/repos/polytunnel-monitor/venv/lib/python3.10/site-packages/flask/cli.py"</cite>,
      line <em class="line">265</em>,
      in <code class="function">locate_app</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">        </span>__import__(module_name)</pre>
<pre class="line before"><span class="ws">    </span>except ImportError as e:</pre>
<pre class="line before"><span class="ws">        </span># Reraise the ImportError if it occurred within the imported module.</pre>
<pre class="line before"><span class="ws">        </span># Determine this by checking whether the trace has a depth &gt; 1.</pre>
<pre class="line before"><span class="ws">        </span>if sys.exc_info()[2].tb_next:</pre>
<pre class="line current"><span class="ws">            </span>raise NoAppException(</pre>
<pre class="line after"><span class="ws">                </span>f&quot;While importing {module_name!r}, an ImportError was raised.&quot;</pre>
<pre class="line after"><span class="ws">            </span>) from e</pre>
<pre class="line after"><span class="ws">        </span>elif raise_if_not_found:</pre>
<pre class="line after"><span class="ws">            </span>raise NoAppException(f&quot;Could not import {module_name!r}.&quot;) from e</pre>
<pre class="line after"><span class="ws">        </span>else:</pre></div>
</div>
</ul>
  <blockquote>flask.cli.NoAppException: While importing &#x27;app&#x27;, an ImportError was raised.</blockquote>
</div>

<div class="plain">
    <p>
      This is the Copy/Paste friendly version of the traceback.
    </p>
    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):
  File &quot;/home/gsej/repos/polytunnel-monitor/webapi/app.py&quot;, line 9, in &lt;module&gt;
    from temperature_data import getTemperatureData, getTemperatureDataRange,getTemperatureDataRangeDb
ImportError: cannot import name &#x27;getTemperatureDataRangeDb&#x27; from &#x27;temperature_data&#x27; (/home/gsej/repos/polytunnel-monitor/webapi/modules/temperature_data.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File &quot;/home/gsej/repos/polytunnel-monitor/venv/lib/python3.10/site-packages/flask/cli.py&quot;, line 363, in __call__
    rv = self._load_unlocked()
  File &quot;/home/gsej/repos/polytunnel-monitor/venv/lib/python3.10/site-packages/flask/cli.py&quot;, line 350, in _load_unlocked
    self._app = rv = self.loader()
  File &quot;/home/gsej/repos/polytunnel-monitor/venv/lib/python3.10/site-packages/flask/cli.py&quot;, line 406, in load_app
    app = locate_app(self, import_name, name)
  File &quot;/home/gsej/repos/polytunnel-monitor/venv/lib/python3.10/site-packages/flask/cli.py&quot;, line 265, in locate_app
    raise NoAppException(
flask.cli.NoAppException: While importing &#x27;app&#x27;, an ImportError was raised.</textarea>
</div>
<div class="explanation">
  The debugger caught an exception in your WSGI application.  You can now
  look at the traceback which led to the error.  <span class="nojavascript">
  If you enable JavaScript you can also use additional features such as code
  execution (if the evalex feature is enabled), automatic pasting of the
  exceptions and much more.</span>
</div>
      <div class="footer">
        Brought to you by <strong class="arthur">DON'T PANIC</strong>, your
        friendly Werkzeug powered traceback interpreter.
      </div>
    </div>

    <div class="pin-prompt">
      <div class="inner">
        <h3>Console Locked</h3>
        <p>
          The console is locked and needs to be unlocked by entering the PIN.
          You can find the PIN printed out on the standard output of your
          shell that runs the server.
        <form>
          <p>PIN:
            <input type=text name=pin size=14>
            <input type=submit name=btn value="Confirm Pin">
        </form>
      </div>
    </div>
  </body>
</html>

<!--

Traceback (most recent call last):
  File "/home/gsej/repos/polytunnel-monitor/webapi/app.py", line 9, in <module>
    from temperature_data import getTemperatureData, getTemperatureDataRange,getTemperatureDataRangeDb
ImportError: cannot import name 'getTemperatureDataRangeDb' from 'temperature_data' (/home/gsej/repos/polytunnel-monitor/webapi/modules/temperature_data.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gsej/repos/polytunnel-monitor/venv/lib/python3.10/site-packages/flask/cli.py", line 363, in __call__
    rv = self._load_unlocked()
  File "/home/gsej/repos/polytunnel-monitor/venv/lib/python3.10/site-packages/flask/cli.py", line 350, in _load_unlocked
    self._app = rv = self.loader()
  File "/home/gsej/repos/polytunnel-monitor/venv/lib/python3.10/site-packages/flask/cli.py", line 406, in load_app
    app = locate_app(self, import_name, name)
  File "/home/gsej/repos/polytunnel-monitor/venv/lib/python3.10/site-packages/flask/cli.py", line 265, in locate_app
    raise NoAppException(
flask.cli.NoAppException: While importing 'app', an ImportError was raised.

-->
